### PR TITLE
Implement viewmodel and common fragment for loading state

### LINKED ISSUE #16: Make a general base fragment for the fragments with loading layout.
Currently, PopularTagsFragment, BrowseFragment, SearchFragment and WallpaperDetail Fragment all have the same code to show loading layout in their viewmodels. We need to create a new base fragment with a viewmodel which would be only responsible to show the loading layout. We can then inherit this fragment into other fragments which require to show the loading layout.

### PR DESCRIPTION
**Pull request by dhruvnagarajan**
Implement CommonViewModel that hosts loading state. Implement corresponding CommonFragment that listens to this loading state.

closes #16

### CODE REVIEW

**Review by justdvnsh — CHANGES_REQUESTED** [review]
hi @dhruvnagarajan can you add a screenshot of the same. Thanks

**Comment by dhruvnagarajan** [comment]
Which screenshot is required?

**Comment by dhruvnagarajan** [comment]
I read somewhere screenshot was required but couldn't find the article now.

**Comment by justdvnsh** [comment]
Hi @dhruvnagarajan Yes. You just need to add a screen recorded video or screenshot that everything is working as expected, i.e. the loading state is working as ususal

**Comment by dhruvnagarajan** [comment]
Got it.

**Comment by dhruvnagarajan** [comment]
Here.

ss_loading

**Comment by dhruvnagarajan** [comment]
UI tests would be seamless instead of ss.

**Comment by justdvnsh** [comment]
> UI tests would be seamless instead of ss.

Yeah. It would, However, we have integrated the tests yet. We will be adding them soon.

**Review by justdvnsh — APPROVED** [review]
Hi @dhruvnagarajan Thanks for the contributions

**Pull request merged**
