### PR TITLE
settings_page

### PR DESCRIPTION
**Pull request by AdiAr11**
I've added the Support Us button addressing issue #9 and improved the UI a little

### CODE REVIEW

**Comment by AdiAr11** [comment]
video demo of above changes

https://user-images.githubusercontent.com/54585121/137493013-add61e28-f258-4574-82ec-d076223195b3.mp4

**Review by justdvnsh — CHANGES_REQUESTED** [review]
Hi @AdiAr11 . The code looks good to me and the UI is also looking very good. Just change the settings title to left as done in other pages. Also, do you mind doing the same in AnimeClassroom project ? You can create a new issue and tag me. i'll assign it to you. The UI is looking god, and we can go with the same UI in AnimeClassroom also. Thank you for your contributions Also, resolve the merge conflicts. Thanks

**Comment by AdiAr11** [comment]
Sure, I'll do the mentioned changes. Also I'll be create a new issue to change the UI in AnimeClassroom project. I'm glad you liked it.

**Comment by AdiAr11** [comment]
I've added Change Theme clipart, fixed Settings page and resolved the conflicts.

**Comment by justdvnsh** [comment]
@AdiAr11 Thank you for your contribution.

**Pull request merged**
