### PR TITLE
Splash screen

### PR DESCRIPTION
**Pull request by AdiAr11**
I've implemented the Splash Screen using Lottie animation addressing issue #5

### CODE REVIEW

**Comment by AdiAr11** [comment]
https://user-images.githubusercontent.com/54585121/137620587-439d8239-70cd-4c77-a7bf-626073203d7e.mp4

Splash Screen demo

**Comment by AdiAr11** [comment]
I somehow couldn't change font though

**Review by justdvnsh — APPROVED** [review]
Hi @AdiAr11 Thank you for your contributions. don't mind the font. That can be changed later. The screen however is looking sassy. Thanks again

**Comment by AdiAr11** [comment]
> Hi @AdiAr11 Thank you for your contributions. don't mind the font. That can be changed later. The screen however is looking sassy. Thanks again

Thank you so much!! I'm so glad you liked it

**Pull request merged**
